version: "3.8"

services:

    db:
        image: postgres:12
        ports:
          - "5432:5432"
        env_file:
          - db.env
        volumes:
          - ./postgresql:/var/lib/postgresql/data
    backend:
        build: ./regula
        ports:
          - "8000:8000"
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
        depends_on:
          - "db"

